import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    slug: "asr-homes",
    name: "ASR Homes",
    stage: "Trust",
    discipline: "Website",
    headline: "The work was premium. The website wasn't.",
    body: "Prospective customers were judging the business by the weakest thing they could find. We rebuilt how the work is presented.",
    actionLabel: "Visit the site",
    href: "https://asrgroupindia.in",
    status: "public",
    external: true,
    image: "/work/asr.jpg",
    imageAlt: "The ASR Group website, showing turnkey interiors and infrastructure projects.",
  },
  {
    slug: "arignya",
    name: "Arignya",
    stage: "Understanding",
    discipline: "Website",
    headline: "Solar sells confidence, not panels.",
    body: "Homeowners had questions long before they had confidence. We made the offer clear and gave them a direct next step.",
    actionLabel: "Visit the site",
    href: "https://www.arignyagreenenergy.com",
    status: "public",
    external: true,
    image: "/work/arignya.jpg",
    imageAlt: "The Arignya Green Energy website, explaining residential rooftop solar.",
  },
  {
    slug: "airakonnect",
    name: "AiraKonnect",
    stage: "Demand",
    discipline: "Foundation · Content · Amplification",
    headline: "A screen network nobody could evaluate.",
    body: "Advertisers had no clear way to judge the network. We built the commercial foundation, then the content, and now the amplification that turns attention into enquiries.",
    actionLabel: "Visit AiraKonnect",
    href: "https://airakonnect.com",
    status: "in-progress",
    external: true,
    image: "/work/airakonnect.jpg",
    imageAlt: "AiraKonnect, the hyperlocal digital out-of-home network Situa builds demand for.",
    imageZoom: 1.45,
    stamp: "Ongoing",
  },
  {
    slug: "lalitha-devi-hospital",
    name: "Lalitha Devi Hospital",
    stage: "Service",
    discipline: "Internal system",
    headline: "Simple for the family. Manageable for the front desk.",
    body: "A membership only works if patients find it effortless and staff don\u2019t drown in it. We built the system behind records, cards, and benefit usage.",
    actionLabel: "Read the case study",
    status: "private",
    image: "/work/lalitha-devi-hospital-dashboard.png",
    imageAlt: "Redacted dashboard showing family membership cards, service activity, and benefit usage for a hospital front desk.",
    stamp: "Private system — redacted",
  },
  {
    slug: "car-rental-crm",
    name: "Car-rental CRM",
    stage: "Conversion",
    discipline: "Internal system",
    headline: "Enquiries were dying between conversations.",
    body: "Interest arrived by call, message, and walk-in — then got lost. We built one place to move a rental forward.",
    actionLabel: "Read the case study",
    status: "private",
    image: "/work/car-rental-crm-dashboard.png",
    imageAlt: "Redacted car-rental CRM dashboard showing enquiries moving from first contact to confirmed rental.",
    stamp: "Private system — redacted",
  },
];
